spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring-security-jwt-auth?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    access-token:
      expiration: 3600000 #una hora
    refresh-token:
      expiration: 604800000 #una semana
    account-validation:
      expiration: 300000 # 5 minutos
    secret: ${AUTH_SECRET:cGxhbnRyaWJlbGlrZWx5cGlua2VsZXBoYW50YmVoYWxmd2F5c3BhY2V0ZWxldmlzaW8=} #NO USAR EN PRODUCCION

backend:
  baseUrl: ${BACKEND_BASE_URL:http://localhost:8080}

