spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring-security-jwt-auth?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    expiration: 86400000 #un dia
